name: Maven Build

on:
  push:
    branches:
      - '*'

jobs:
  fetch_shared_commit_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: sachin-smartbear/project_Shared
          ref: master
          token: ${{ secrets.TOKEN }}

      - name: Get last commit ID
        id: last_commit
        run: echo "::set-output name=commit_id::$(git log -1 --pretty=format:%H)"

    outputs:
      commit_id: ${{ steps.last_commit.outputs.commit_id }}

  resolve_shared_dependency:
    runs-on: ubuntu-latest
    needs: [fetch_shared_commit_id]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Configure Maven settings
        run: echo "<settings><servers><server><id>github-ready</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server><server><id>github-shared</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml

      - name: resolve shared dependency
        run: mvn dependency:resolve -DincludeArtifactIds=project_shared -Dshared_version=SNAPSHOT-${{ needs.fetch_shared_commit_id.outputs.commit_id }}
        continue-on-error: true

  build_SHARED:
    runs-on: ubuntu-latest
    needs: [resolve_shared_dependency, fetch_shared_commit_id]
    if: ${{ needs.resolve_shared_dependency.failure()}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: sachin-smartbear/project_Shared
          ref: master
          token: ${{ secrets.TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Configure Maven settings
        run: echo "<settings><servers><server><id>github-shared</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
      - name: Build SHARED with Maven
        run: mvn deploy -Dcommit_id=-${{ needs.fetch_shared_commit_id.outputs.commit_id }}
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

#  build_READY:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          repository: sachin-smartbear/project_ready
#          ref: master
#          token: ${{ secrets.TOKEN }}
#
#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#      - name: Configure Maven settings
#        run: echo "<settings><servers><server><id>github-ready</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
#      - name: Build Ready with Maven
#        run:  mvn clean install deploy
#        env:
#          GITHUB_USERNAME: ${{ secrets.USERNAME }}
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  build_X:
    runs-on: ubuntu-latest
    needs: [build_SHARED]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Configure Maven settings
        run: echo "<settings><servers><server><id>github-ready</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server><server><id>github-shared</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
      - name: Build X with Maven
        run: mvn clean install -Dshared_version=SNAPSHOT-${{ needs.fetch_shared_commit_id.outputs.commit_id }}
      # Add additional steps if needed for project X
