name: Maven Build

on:
  push:
    branches:
      - '*'

jobs:
  build_READY:
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.r_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: sachin-smartbear/project_ready
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Ready with Maven
        run:  mvn clean install deploy
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  build_SHARED:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: sachin-smartbear/project_Shared
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get last commit ID
        id: last_commit
        run: echo "::set-output name=commit_id::$(git log -1 --pretty=format:%H)"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build SHARED with Maven
        run: mvn clean install deploy -Dcommit_id=-${{ steps.last_commit.outputs.commit_id }}
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  build_X:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Configure Maven settings
        run: echo "<settings><servers><server><id>github-ready</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server><server><id>github-shared</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
      - name: Build X with Maven
        run: mvn clean install -Dshared_version=-SNAPSHOT-${{ steps.build_SHARED.last_commit.outputs.commit_id }}
      # Add additional steps if needed for project X
