name: Maven Build

on:
  push:
    branches:
      - '*'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      r_changed: ${{ steps.r_changes.outputs.changed }}
      ts_changed: ${{ steps.ts_changes.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check R changes
        id: r_changes
        run: |
          git diff --quiet HEAD~1..HEAD sachin-smartbear/project_ready || echo "::set-output name=changed::true"

      - name: Check TS changes
        id: ts_changes
        run: |
          git diff --quiet HEAD~1..HEAD sachin-smartbear/project_Shared || echo "::set-output name=changed::true"
  build_READY:
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.r_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: sachin-smartbear/project_ready
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Ready with Maven
        run:  mvn clean install deploy
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  build_SHARED:
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.ts_changed == 'true'
    needs: build_READY
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: sachin-smartbear/project_Shared
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build SHARED with Maven
        run: mvn clean install deploy
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  build_X:
    runs-on: ubuntu-latest
    needs: [build_READY, build_SHARED]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Configure Maven settings
        run: echo "<settings><servers><server><id>github-ready</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server><server><id>github-shared</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
      - name: Build X with Maven
        run: mvn clean install
      # Add additional steps if needed for project X
